<?php
session_start();
?>
<html>
<head><title>
	Invoice Generator - Mailing
</title></head>
<body>
<?php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
require 'PHPMailer/src/Exception.php';
require 'PHPMailer/src/PHPMailer.php';
require 'PHPMailer/src/SMTP.php';
$mail = new PHPMailer();
$mail->IsSMTP();
$mail->SMTPDebug = 0;
$mail->SMTPAuth = TRUE;
$mail->SMTPSecure = "tls";
$mail->Port     = 587;  
$mail->Username = "csenmamit@gmail.com";
$mail->Password = "faraz@2020";
$mail->Host     = "smtp.gmail.com";
$mail->Mailer   = "smtp";
$mail->SetFrom("csenmamit@gmail.com",$_SESSION["company"]);
$mail->AddReplyTo($_SESSION['Uemail'],$_SESSION["company"]);
//$mail->AddReplyTo("karthikukumar786@gmail.com", "Karthik");
$mail->AddAddress($_SESSION['customermail']);

$mail->AddAddress("farazsashaikh@gmail.com");
$mail->Subject = "Invoice from ".$_SESSION["company"];
$mail->WordWrap   = 150;
$content = "<b>Invoice Number ".$_SESSION['orderid']." has been generated by ".$_SESSION['company']."</b><br>Total Amount= ".$_SESSION['total']."<br>Amount in words= ".$_SESSION['words']."<br>Items purchased are ".$_SESSION['items'];
$mail->MsgHTML($content);
$mail->IsHTML(true);
if(!$mail->Send())
echo "<script>alert(\"Please check your email-id\");
        window.location='bill.php'; </script>";
else
echo "<script>alert(\"Mail Sent.\");
        window.location='bill.php' </script>";
?>
</body>
</html>
